### ISSUE TITLE
Warmup Cancelled for All Players on Any Player Movement

### ISSUE THREAD

**Issue by Jujinko** [DownThePark/SetHome#13]
Issue Description:
Theplugin has a feature where certain commands have a warmup period that can be cancelled if the player moves. However, we're encountering an issue where if any player moves, it cancels the warmup for all players, not just the player who moved. This is impacting the gameplay experience as players are unable to use commands like sethome, home, and deletehome properly if they have a warmup time/cancel warmup on move.

Steps to Reproduce:
Two players, Player A and Player B, are on the server. The /home command is configured in a way that has a warmup window and cancels on move during warmup.
Player A executes the sethome command, initiating a warmup period.
Player B moves during Player A's warmup period.
Player A's warmup gets cancelled even though they did not move.
Player B gets the cancel message.

Expected Behavior:
The warmup period for a command should only be cancelled if the player who executed the command moves.

Actual Behavior:
Any player's movement cancels the warmup periods for all players on the server.

Possible Solution:
The issue seems to stem from how the warmup tasks are being managed. Currently, the warmup cancellation is seemingly not player-specific. A suggested solution is to modify the warmup management to track warmup tasks on a per-player basis. This involves changing the data structure of warmupInEffect and warmupTask to map from COMMAND_TYPE to another HashMap that associates each player (or their UUID) with their warmup state and task.

Additional Context:
Here's the part of the code that presumably needs to be reviewed:
`public class EventMove implements Listener {

    @EventHandler
    public void onPlayerMove(PlayerMoveEvent event) {
        if (SetHome.getInstance().configUtils.CMD_SETHOME_WARMUP_CANCEL_ON_MOVE) {
            cancelMove(CommandExecutor.COMMAND_TYPE.SETHOME, event.getPlayer());
        }
        if (SetHome.getInstance().configUtils.CMD_HOME_WARMUP_CANCEL_ON_MOVE) {
            cancelMove(CommandExecutor.COMMAND_TYPE.HOME, event.getPlayer());
        }
        if (SetHome.getInstance().configUtils.CMD_DELETEHOME_WARMUP_CANCEL_ON_MOVE) {
            cancelMove(CommandExecutor.COMMAND_TYPE.DELETEHOME, event.getPlayer());
        }
    }

    private void cancelMove(CommandExecutor.COMMAND_TYPE commandType, Player player) {
        if (CommandExecutor.getWarmupInEffect().get(commandType)) {
            CommandExecutor.getWarmupInEffect().put(commandType, false);
            CommandExecutor.getWarmupTask().get(commandType).cancel();
            SetHome.getInstance().messageUtils.displayMessage(MessageUtils.MESSAGE_TYPE.ON_MOVE, player, null);
        }
    }

}`

**Comment by DownThePark** [comment]
Hello, @Jujinko !

Thank you for the detailed bug report. This should now be fixed now in the latest commits.

Would you mind testing out the new code and reporting back if it now works or not?

Regards,
DownThePark
[SetHome-6.2.1.jar.zip](https://github.com/DownThePark/SetHome/files/13854371/SetHome-6.2.1.jar.zip)

**Comment by Jujinko** [comment]
Thank you for the quick response time @DownThePark !

I have just updated to the newest version and reenabled the warmup in my config.
We will test the fix and and take feedback from our players. Thank you again for the quick fix!

**Comment by Jujinko** [comment]
I have replaced the jar with the latest release version 6.2.1 but I still encounter the bug. But I have discovered that my console outputs `[22:49:13 INFO]: [SetHome] SetHome Remote version: 6.2.0`. So I can't rule out the possibility that it might be an error on my end. I will make a clean install of the plugin and report back.

**Comment by DownThePark** [comment]
The "remote version" and "local version" status usually takes about a day to update.
Anyhow, I just released another update here. If clean installing 6.2.1 doesn't work for you, installing 6.2.2 _might_ fix the issue. Do keep me updated!
[SetHome-6.2.2.jar](https://github.com/DownThePark/SetHome/releases/download/v6.2.2/SetHome-6.2.2.jar)

**Comment by DownThePark** [comment]
@Jujinko 
Alright! I've got it fixed for sure now! The problem was that using static variables to temporarily store data was creating misleading data, so the solution was to get rid of those variables and just create temporary variables in the functions that create the data. Idk what I was thinking publishing a new release that wasn't properly tested... I apologize again for the inconvenience.

Would you mind testing it out SetHome v6.2.2 and reporting your results, please and thank you?

DownThePark
[SetHome-6.2.2.jar](https://github.com/DownThePark/SetHome/releases/download/v6.2.2/SetHome-6.2.2.jar)

**Comment by Jujinko** [comment]
Sorry for the wait, I was very busy the last few days. I have updated the server to the newest version and reach out to you later today once I have confirmed your finds and close the issue. Thank you again for you quick and dedicated work!
